name: CI-CD Google Skills Boost Final

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy Cloud Function
        uses: 'google-github-actions/deploy-cloud-functions@v2'
        with:
          name: data-cleaner-lab
          runtime: python310
          region: europe-west4
          source_dir: ./app
          entry_point: clean_data_trigger
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: projects/${{ secrets.GCP_PROJECT_ID }}/buckets/${{ secrets.GCP_PROJECT_ID }}